9월 15일 스택, 큐, 덱 과제 제출
Altu-Bitu-3/Altu-Bitu-HanbyChoi pull request #3
Opened 2022-09-15 02:57 UTC by hanby-choi

#### 내용 & 질문
> 제출합니다. 17299가 시간초과가 나서 해결하는 대로 다시 올리겠습니다

#### <기존 제출>
> 11866, 17299

#### <추가 제출>
>

2022-09-15 17:53 UTC, jk0527 reviewed
**P2. 11866 코드리뷰 완료**

한비님 안녕하세요! 문제 정말 잘 풀어주셨어요!!😎😎
함수화와 출력 관련하여 사소한 코멘트 남겼습니다!!
궁금한 점이 있으면 리뷰어 호출해주세요!! 수고하셨습니다!

2022-09-15 17:53 UTC, jk0527 commented on 9월 9일 - 스택, 큐, 덱/11866.cpp
> +    while (q.size() > 1){
연산을 하는 부분은 함수화해도 좋을 것 같아요. 함수에서 vector에 원소를 순서대로 저장하고
vector를 main에서 받아서 한 번에 출력하면 어떨까요?

2022-09-15 17:53 UTC, jk0527 commented on 9월 9일 - 스택, 큐, 덱/11866.cpp
> +        } else if (cnt % k == 0){ // k번째 수에 대해
else if 말고 else 써도 될 것 같아요!

2022-09-15 17:53 UTC, jk0527 commented on 9월 9일 - 스택, 큐, 덱/11866.cpp
> +            q.pop(); // k번째 수를 제거
q.pop()은 if와 else 조건 모두에 있네요! 밖으로 빼도 될 것 같아요!!

2022-09-15 21:06 UTC, jaeseo222 requested changes
**p1. 17299 코드 리뷰 완료**

안녕하세요 한비님🤗
쉽지 않은 문제였는데, 너무 잘 풀어주셨습니다!!

가독성에 관한 피드백 및 수정해주실 부분에 대한 코멘트 달았으니, 확인 부탁 드립니다 !
백준에서 맞았습니다!가 떠야 제출 인정되는 점 유의 바랍니다.😉😉

p1은 꼭 수정 부탁 드리며, p2와 p3는 자유로이 수정해주시면 됩니다.
**수정하신 부분 있으시면 리뷰어로 불러주세요!**
수고 많으셨습니다. 감사합니다.😄😄

2022-09-15 21:06 UTC, jaeseo222 commented on 9월 9일 - 스택, 큐, 덱/17299.cpp
> +    }
p2. 개인 취향 차이겠지만..! 가독성 면에서 피드백 남깁니다.😉

입력된 숫자와 등장한 횟수 처리를 한 번에 입력 할 수 있을 것 같아요!
**num**은 **크기가 n**인 것을 아니까, **선언과 동시에 초기화**해줄 수 있을 것 같아요. 그렇다면 입력할 때 `num[i]`에 바로 참조 가능하겠네요! 😉
한편 **cnt**는 크기가 딱 정해지진 않았지만, 문제의 조건에 나온 대로 **수열 A의 원소의 최대 크기**를 고려해볼까요! 최대 크기는 1,000,000이니까 1,000,000만큼 초기화 해 놓고, 등장한 횟수를 알아야 하는 숫자만 참조해도 괜찮겠어요!!

2022-09-15 21:06 UTC, jaeseo222 commented on 9월 9일 - 스택, 큐, 덱/17299.cpp
> +    }
p1. 현재 반복문 depth가 깊어진 것 같아요!

현재, **각각의 모든 숫자마다** 오등큰수가 될 수 있는 숫자들을 저장한 후 비교해가며 오등큰수를 정해주고 계시네요! 직관적으로 와 닿을 수 있는 해결 방법인 반면, 각각의 숫자에 대해 다 처리 하다 보니 시간이 오래 걸리는 문제가 생기네요🥺

stack의 장점을 고려해볼까요? 아시겠지만, **맨 오른쪽 수부터 쌓다 보면, 맨 왼쪽 수에서 stack의 top이 가장 왼쪽에 있는 수가 되겠네요.**
그럼 만약, **top이 등장한 횟수가 가장 큰 수**라면 top을 제외한 stack에 있는 수들은 더 이상 필요 있을까요?
문제의 조건처럼, **현재 원소보다 등장한 횟수가 큰 수 중에서 가장 왼쪽에 있는 수** == **top** 이라는 의미가 되겠네요!
그럼, top이 가장 왼쪽에 있는 수니까 top보다 오른쪽에 있는 수는 선택될 일이 없겠네요!!😉🔥

결과적으로, 맨 오른쪽부터 **현재 검사하는 원소의 등장한 횟수보다 더 작은 원소들을 만났을 때 어떻게 해줘야 할까요?**

2022-09-28 10:12 UTC, jaeseo222 reviewed
리뷰를 늦게 드린 제 불찰로 인해, 번거로운 일을 겪게 하여 죄송합니다!!! 😭😭😭
다음엔 꼭 이런 일 없도록 하겠습니다!!

**17299 코드리뷰 완료**입니다.
사소한 코멘트 남겼으니, 확인 후 머지 해주셔도 될 것 같습니다.

수고 너무 많으셨습니다. 감사합니다!

2022-09-28 10:12 UTC, jaeseo222 commented on 9월 9일 - 스택, 큐, 덱/17299.cpp
> +    vector<int> num(n, 0), cnt(1000001, 0), result; // 선언과 동시에 크기 지정
p3. 사소하지만 **1000001** 처럼 특정 크기같이 의미 있는 수는 여러 번 사용될 때가 있으니까 상수로 선언 후, 사용해주시면 좋을 것 같습니다 !

2022-09-28 15:35 UTC, merged